spring:
  application:
    name: taskmanager
  datasource:
    url: jdbc:postgresql://localhost:5432/taskdb
    username: postgres
    password: Maroon
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true
