spring:
  application:
    name: taskmanager
    admin-token: ${ADMIN_TOKEN}

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  server:
    port: 8080

  jwt:
    secret: ${JWT_SECRET}

