spring:
  application:
    name: taskmanager

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: ${PORT:8080}

jwt:
  secret: ${JWT_SECRET}

app:
  admin-token: ${ADMIN_TOKEN}
  ADMIN_PASSWORD: ${ADMIN_PASSWORD}